### ISSUE TITLE
estru3D is not anymore compatible with qt4 webkit

### ISSUE THREAD

**Issue by penguin31** [tercoide/estru3d#1]
estru3D downloaded by https://sourceforge.net/projects/estru3d/files/
Cannot be installed anymore because Debian has deprecated qt4 webkit in favor of qt5 webkit.
Can you recompile it for qt5 ?

**Comment by tercoide** [comment]
Hello. I'm sorry fot the late response. I was following the project at Sourceforge and totally forgot about this. It will be ported to Qt5 soon. In case you are still around , let me know.
